### ISSUE TITLE
移除部分 Google 相关？

### ISSUE THREAD

**Issue by SerCom-KC** [gfwlist/gfwlist#682]
- [x] ```www.recaptcha.net```
- [x] ```recaptcha.net```
- [ ] ```www.gstatic.com```
- [x] ```redirector.gvt1.com```

暂时只想到以上几个，但这些在国内目前都已经解析到北京谷翔的服务器了
大陆应该都是能正常使用的

**Comment by SerCom-KC** [comment]
追加一个```tools.google.com```

**Comment by cicku** [comment]
+1 for the syntax! :smirk: TY!

**Comment by ZenFX** [comment]
Google还有不少域名都解析到Google国内服务器了

update.googleapis.com
clientservices.googleapis.com

www.gstatic.com
ssl.gstatc.com
connectivitycheck.gstatic.com

还有好多没列出来，可以参考这个：
https://github.com/felixonmars/dnsmasq-china-list/blob/master/google.china.conf

**Comment by paperbag** [comment]
再补一个
```
  "@@||translate.googleapis.com",
```

**Comment by SerCom-KC** [comment]
慢着，似乎有极个别地区的解析又跑到国外了（包括 `.cn`）
这个 issue 先缓一缓吧……

**Comment by cicku** [comment]
我一点都不着急。

更何况部分汇报本身就有问题，我一直没处理，正好观测一阵。不然早就关了这个 issue 了。

**Comment by cicku** [comment]
`||gstatic.com`:

Exception raised for: `t0.gstatic.com`, `maps.gstatic.com`, `mail.gstatic.com`, `accounts.gstatic.com`.

**Comment by SerCom-KC** [comment]
好吧，是我太紧张了😅应该是谷歌解析的锅，现在恢复了

**Comment by cicku** [comment]
等 BRICKS 开完继续处理

**Comment by aoisummer** [comment]
`dl.google.com`

**Comment by paperbag** [comment]
这个已经在白名单里了。@aoisummer

On September 22, 2017 6:10:47 PM GMT+08:00, aoisummer <notifications@github.com> wrote:
>`dl.google.com`

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by XinSSS** [comment]
我觉得google相关的移除还是谨慎一些? 说不准哪天又抽风了...做个备份也行

**Comment by paperbag** [comment]
其实没有移除，只是通过规则把一些域名给排除出去了，类似于白名单。@XinSSS

下面是几个例子，摘自 gfwlist：
```
@@||dl.google.com
@@||kh.google.com
@@||khm.google.com
@@||khm0.google.com
@@||khm1.google.com
@@||khm2.google.com
@@||khm3.google.com
@@||khmdb.google.com
@@||tools.google.com
@@||fonts.googleapis.com
```

**Comment by SerCom-KC** [comment]
嘛，反正估计再过两三年又得全部加回来（笑）
不可能移除的

**Comment by crifan** [comment]
背景：
从ShadowsocksX换成了ShadowsocksX-NG，自动模式下，发现死活无法加载
https://analytics.google.com/analytics/web
的内容。
调试了半天发现：
最新的此处gfwlist，竟然把部分的google的地址，尤其是：
fonts.googleapis.com
等地址，都用@@ 注释掉了。。。
但是实际上这些网站，现在 2017-10-12，又都无法访问了
-》可以确定在不久的将来，早晚还是会被封的
-》所以之前那些去掉，目前暂时解封的 google的地址的做法，明显就不靠谱
-》
# 希望尽快恢复这些google地址，确保是走代理的

**Comment by paperbag** [comment]
我这里都正常的啊，`fonts.googleapis.com`你是解析到哪里？@crifan

**Comment by crifan** [comment]
@paperbag 
```
➜  shadowsocks ping fonts.googleapis.com
PING googleadapis.l.google.com (203.208.39.226): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- googleadapis.l.google.com ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```

我这里
```
https://fonts.googleapis.com
https://www.googletagmanager.com
https://ssl.gstatic.com
```
都是pending状态，网页都无法加载。
我这里是：江苏苏州 电信

**Comment by paperbag** [comment]
大概是线路问题把，国内其他地方基本上都可以访问 @crifan 
你提到的 `203.208.39.226`：
http://www.17ce.com/site/ping/201710_a2b0d30758c60bcf22b8e596d9d3da12.html
http://www.17ce.com/site/http/201710_6436a91b835780148b24b8f644c6de70.html

**Comment by Elepover** [comment]
fonts.gstatic.com

也可以了。

**Comment by cicku** [comment]
```
fonts.gstatic.com

也可以
```

什么可以???

**Comment by mxlife** [comment]
这个域名也解析到Google国内服务器了
safebrowsing.googleapis.com

**Comment by paperbag** [comment]
赞！之前 Chrome 和 Firefox 的安全浏览功能都因为无法访问而导致下载开始或结束时有卡顿。

**Comment by paperbag** [comment]
`storage.googleapis.com` 解析又回到国外了😞。

**Comment by cicku** [comment]
Really?
